/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class UserAccount extends javax.swing.JFrame {
     private String fname, contact, bdate, mail, address,username,password,userName, email;
    private ImageIcon userImage;
    private int userId;
    private ImageIcon usersImage;

    /**
     * Creates new form UserAccounts
     */
    public UserAccount(String fname, String contact, String bdate, String mail, String address, String username, String password, String userName, ImageIcon userImage, String emai1) {
        initComponents();
        
         this.fname = fname;
        this.contact = contact;
        this.bdate = bdate;
        this.mail = mail;
        this.address = address;
        this.username = username;
        this.password = password;
        this.userName = userName;
        this.userImage = userImage;
        this.email = email;
        
        // Assign the values to JLabels
        Fullname.setText(fname);
        Contact.setText(contact);
        Birthday.setText(bdate);
        Email.setText(mail);
        Address.setText(address);
        Username.setText(username);
        Password.setText(password);
        
        if (userImage != null) {
            View_User_Pic.setIcon(userImage);
        }
    }
    public UserAccount() {
        initComponents();
        Fullname.setText("");  // Set default empty text
        Contact.setText("");
        Birthday.setText("");
        Email.setText("");
        Address.setText("");
        Username.setText("");
        Password.setText("");
        
    }
    public void updateUserInfo( String fname, String contact, String bdate, String mail, String address, String username, String password, String userName) {
    // Update fields in the UserAccount window
    this.Fullname.setText(fname); // Adjusted to match your field names
    this.Contact.setText(contact);
    this.Birthday.setText(bdate);
    this.Email.setText(mail);
    this.Address.setText(address);
    this.Username.setText(username);
     this.Password.setText(password);
 
   
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserPanel = new javax.swing.JPanel();
        View_User_Pic = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Birthday = new javax.swing.JLabel();
        Fullname = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        User_Back = new javax.swing.JButton();
        Username1 = new javax.swing.JLabel();
        Password1 = new javax.swing.JLabel();
        Full_name = new javax.swing.JLabel();
        ContactNo = new javax.swing.JLabel();
        bdate2 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        UserPanel.setBackground(new java.awt.Color(255, 255, 204));
        UserPanel.setPreferredSize(new java.awt.Dimension(475, 580));

        View_User_Pic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        View_User_Pic.setMaximumSize(new java.awt.Dimension(150, 150));
        View_User_Pic.setMinimumSize(new java.awt.Dimension(150, 150));
        View_User_Pic.setPreferredSize(new java.awt.Dimension(150, 150));

        Username.setBackground(new java.awt.Color(0, 0, 0));
        Username.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Contact.setBackground(new java.awt.Color(0, 0, 0));
        Contact.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Birthday.setBackground(new java.awt.Color(0, 0, 0));
        Birthday.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Fullname.setBackground(new java.awt.Color(0, 0, 0));
        Fullname.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Password.setBackground(new java.awt.Color(0, 0, 0));
        Password.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        Address.setBackground(new java.awt.Color(0, 0, 0));
        Address.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 194, 194)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 87, 87));
        jLabel2.setText("My Profile");

        User_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        User_Back.setText("<");
        User_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        User_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        User_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_BackActionPerformed(evt);
            }
        });

        Username1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Username1.setForeground(new java.awt.Color(62, 62, 62));
        Username1.setText("Username");

        Password1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Password1.setForeground(new java.awt.Color(62, 62, 62));
        Password1.setText("Password");

        Full_name.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Full_name.setForeground(new java.awt.Color(62, 62, 62));
        Full_name.setText("Full Name");

        ContactNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ContactNo.setForeground(new java.awt.Color(62, 62, 62));
        ContactNo.setText("Contact No.");

        bdate2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        bdate2.setForeground(new java.awt.Color(62, 62, 62));
        bdate2.setText("Birthday");

        Email1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Email1.setForeground(new java.awt.Color(62, 62, 62));
        Email1.setText("Email");

        Address1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Address1.setForeground(new java.awt.Color(62, 62, 62));
        Address1.setText("Address");

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(View_User_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Full_name))
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserPanelLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(Username1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(UserPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(152, Short.MAX_VALUE))))
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Email1)
                            .addComponent(bdate2)
                            .addComponent(ContactNo)
                            .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(Contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(User_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Username1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Password1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(UserPanelLayout.createSequentialGroup()
                        .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addGroup(UserPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(User_Back)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(View_User_Pic, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Full_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContactNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bdate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jScrollPane1.setViewportView(UserPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void User_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_BackActionPerformed
        // TODO add your handling code here:
        UserSetting setting = new UserSetting(fname, contact, bdate, mail, address, username, password, userName, userImage, email); // Pass back to settings
        setting.setVisible(true);
        setting.pack();
        this.dispose();

    }//GEN-LAST:event_User_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 String fname =null; 
                String contact= null;
                String bdate= null;
                String mail= null;
                String address= null;
                String username = null;
                String password = null;
                String userName = null;
                ImageIcon usersImage = null;
                String email = null;
                new UserAccount(fname, contact, bdate, mail, address, username, password, userName, usersImage, email).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Birthday;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel ContactNo;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Full_name;
    private javax.swing.JLabel Fullname;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password1;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton User_Back;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel View_User_Pic;
    private javax.swing.JLabel bdate2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
