
package admin;
import javax.swing.JFileChooser;
import java.io.File;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Graphics2D;

/**
 *
 * @author rachel
 */
public class AddMenu extends javax.swing.JFrame {
    private String adminName, adID,adpass,adname, adpassword;
    private ImageIcon adminImage;



    public AddMenu(String adminName, ImageIcon adminImage) {
       initComponents();
        this.adminName = adminName;  
        this.adminImage = adminImage;
        
    }
private byte[] tempImageBytes;
    /**
     * Creates new form User_Dashboard
     */
    public AddMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        Edit_Back = new javax.swing.JButton();
        Insert_menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Product_Pic = new javax.swing.JLabel();
        upload_image = new javax.swing.JButton();
        Stocks = new javax.swing.JTextField();
        nothing3 = new javax.swing.JLabel();
        Product_Name = new javax.swing.JTextField();
        nothing2 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        nothing4 = new javax.swing.JLabel();
        Category_Id = new javax.swing.JTextField();
        nothing1 = new javax.swing.JLabel();
        nothing5 = new javax.swing.JLabel();
        inventory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 581));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit_Back.setBackground(new java.awt.Color(73, 73, 73));
        Edit_Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Edit_Back.setForeground(new java.awt.Color(235, 235, 235));
        Edit_Back.setText("Back");
        Edit_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Edit_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Edit_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_BackActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 50, -1));

        Insert_menu.setBackground(new java.awt.Color(233, 243, 249));
        Insert_menu.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        Insert_menu.setText("Add");
        Insert_menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(245, 251, 252), new java.awt.Color(243, 251, 252), new java.awt.Color(243, 249, 249), new java.awt.Color(242, 250, 250)));
        Insert_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_menuActionPerformed(evt);
            }
        });
        jPanel1.add(Insert_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 70, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Edit Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 6, -1, 40));

        Product_Pic.setBackground(new java.awt.Color(102, 102, 102));
        Product_Pic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jPanel1.add(Product_Pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 60, 160, 128));

        upload_image.setBackground(new java.awt.Color(233, 243, 249));
        upload_image.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        upload_image.setText("Upload Image");
        upload_image.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(245, 251, 252), new java.awt.Color(243, 251, 252), new java.awt.Color(243, 249, 249), new java.awt.Color(242, 250, 250)));
        upload_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_imageActionPerformed(evt);
            }
        });
        jPanel1.add(upload_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 89, -1));

        Stocks.setBackground(new java.awt.Color(248, 248, 248));
        Stocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StocksActionPerformed(evt);
            }
        });
        jPanel1.add(Stocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 107, 31));

        nothing3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nothing3.setText("Price");
        jPanel1.add(nothing3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        Product_Name.setBackground(new java.awt.Color(248, 248, 248));
        Product_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Product_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 208, 31));

        nothing2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nothing2.setText("Beginning Inventory");
        jPanel1.add(nothing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        Price.setBackground(new java.awt.Color(248, 248, 248));
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, 31));

        nothing4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nothing4.setText("Stocks");
        jPanel1.add(nothing4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        Category_Id.setBackground(new java.awt.Color(248, 248, 248));
        Category_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Category_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 107, 31));

        nothing1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nothing1.setText("Category ID");
        jPanel1.add(nothing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        nothing5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nothing5.setText("Product Name");
        jPanel1.add(nothing5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        inventory.setBackground(new java.awt.Color(248, 248, 248));
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });
        jPanel1.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Edit_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_BackActionPerformed
        AdminMenu menu = new AdminMenu(adminName, adminImage);   
    menu.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_Edit_BackActionPerformed

    private void Insert_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_menuActionPerformed
        // TODO add your handling code here:
         String categoryId = Category_Id.getText();
    String productName = Product_Name.getText();
    String productPrice = Price.getText();
    String productStocks = Stocks.getText();

    // Validate inputs
    if (categoryId.isEmpty() || productName.isEmpty() || productPrice.isEmpty() || productStocks.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Parse numeric inputs
        double price = Double.parseDouble(productPrice);
        int stocks = Integer.parseInt(productStocks);

        // Use the uploaded image bytes if available
        byte[] imageBytes = tempImageBytes;

        // Establish database connection
        try (Connection conn = CONNECTOR.DBconnect.connect()) {
            // SQL insert query
            String sql = "INSERT INTO Products (categoryID, productName, price, stocks, productImage) VALUES (?, ?, ?, ?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                // Set parameters
                pstmt.setString(1, categoryId);
                pstmt.setString(2, productName);
                pstmt.setDouble(3, price);
                pstmt.setInt(4, stocks);
                pstmt.setBytes(5, imageBytes);

                // Execute the insert operation
                int rowsInserted = pstmt.executeUpdate();
                if (rowsInserted > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Product added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Clear the form for new entries
                    Category_Id.setText("");
                    Product_Name.setText("");
                    Price.setText("");
                    Stocks.setText("");
                    Product_Pic.setIcon(null);
                    upload_image.setText("Upload Image");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to add the product. Please try again.", "Insert Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Price and stocks must be numeric values!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_Insert_menuActionPerformed

    private void upload_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_imageActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
   JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Select an Image");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    // Show the file chooser and get the selected file
    int result = chooser.showOpenDialog(null);

    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = chooser.getSelectedFile();

        try {
            // Read and resize the image
            BufferedImage bi = ImageIO.read(selectedFile);
            Image resizedImage = bi.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            Product_Pic.setIcon(new ImageIcon(resizedImage)); // Display image in label
            upload_image.setText("Image Uploaded");

            // Save image to a temporary byte array (used later in the update button)
            try (FileInputStream fis = new FileInputStream(selectedFile)) {
                byte[] imageBytes = fis.readAllBytes();
                // Store the image bytes temporarily in a class-level variable
                this.tempImageBytes = imageBytes; // Add a class-level variable: private byte[] tempImageBytes;
            }
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Unable to process the image.", "Image Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_upload_imageActionPerformed

    private void StocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StocksActionPerformed
        // TODO add your handling code here
     
    }//GEN-LAST:event_StocksActionPerformed

    private void Product_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_NameActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void Category_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_IdActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Category_Id;
    private javax.swing.JButton Edit_Back;
    private javax.swing.JButton Insert_menu;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Product_Name;
    private javax.swing.JLabel Product_Pic;
    private javax.swing.JTextField Stocks;
    private java.awt.Canvas canvas1;
    private javax.swing.JTextField inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nothing1;
    private javax.swing.JLabel nothing2;
    private javax.swing.JLabel nothing3;
    private javax.swing.JLabel nothing4;
    private javax.swing.JLabel nothing5;
    private javax.swing.JButton upload_image;
    // End of variables declaration//GEN-END:variables
}
